# By default, itzg/minecraft-server will run the selected minecraft server with
# the specified data as the 'minecraft' user, not as root. This improves
# security.

# The official documentation is very thorough:
# https://docker-minecraft-server.readthedocs.io/en/latest/

# Interacting with the server:
#
# Try:
# docker exec -i minecraft_docker_server-mc-1 mc-send-to-console  say hi
# docker attach minecraft_docker_server-mc-1
#
# minecraft_docker_server-mc-1  is the container name, which may be different
# Get the name with: docker container ls
#
# Read https://github.com/itzg/docker-minecraft-server#interacting-with-the-server
# for how to send commands to the server
services:
  mc:
    image: itzg/minecraft-server:java25-graalvm
    stop_grace_period: 1m # Avoid killing too quick to give time to save world files
    ports: # Expose ports
      - 25565:25565 # Minecraft server port.
      - 25575:25575 # RCON port. Do not expose to the internet.
    # Security settings
    security_opt:
      - no-new-privileges:true
      - apparmor:docker-default
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "100"
        compress: "true"
    privileged: false
    deploy:
      resources:
        reservations: # check with `docker stats`
          cpus: 8
          memory: 10G
    tty: true
    stdin_open: true
    # Always restart the container if it stops, unless it was stopped "manually or otherwise"
    restart: unless-stopped
    volumes:
      # Be sure to change $MAP in the scripts too!
      - ./IMPERIUS_FELINUS_server_data:/data # Game data. Make sure to regularly backup!
      - ./logs:/data/logs
    environment:
      # Did you agree to the contract terms in the EULA? No choice!
      EULA: "TRUE"
      MOTD: "Welcome to Felina's undefeatable Thinkpad, enjoy. 😸"
      OVERRIDE_SERVER_PROPERTIES: "true" # This .yml file is the source of truth, beware!
      #
      # TYPE: "PAPER"
      # VERSION: "1.21.4"
      # VERSION: "1.21.11"
      # TYPE: "VANILLA"
      # VERSION: "26.1"
      # TYPE: FORGE
      # VERSION: "26.1.1"  # Find on https://neoforged.net/
      # DO NOT AUTOMATE DOWNLOAD! Forge depends on ad revenue, download the file yourself. Avoid FORGE_VERSION.
      # FORGE_INSTALLER: "./forge-26.1.1-63.0.1-installer.jar"
      #
      VERSION: "26.1"
      USE_AIKAR_FLAGS: "true" # More efficient garbage collection for better performance from aikar's flag generator
      USE_SIMD_FLAGS: "true"
      MAX_TICK_TIME: "-1" # Prevent watchdog killing server
      # Install mods using modrinth
      MODPACK_PLATFORM: "MODRINTH" # Modpacks are simple ways to install groups of mods: https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/modrinth-modpacks/
      MODRINTH_MODPACK: https://modrinth.com/modpack/ovop/version/yJNO4kJ1 # ovop with Minecraft 26.1 and Fabric loader, Overly Optimized https://modrinth.com/modpack/ovop
      # Check game version here: https://modrinth.com/modpack/ovop/versions
      # MODRINTH_MODPACK: ovop
      # MODRINTH_MODPACK_VERSION_TYPE: alpha
      # Mod list from modrinth. Optimizers like lithium, ferrite, servercore, etc are installed via modpack
      # Tectonic - Terrain shaping brought to new heights, grander and more varied than ever before!  # https://modrinth.com/datapack/tectonic
      # Lithostitched Library mod with new configurability and compatibility enhancements for worldgen # https://modrinth.com/mod/lithostitched
      # ViaVersion allows newer clients to connect to older servers # https://modrinth.com/plugin/viaversion
      # ViaBackwards: Allow older Java Edition clients to connect to newer servers.
      # ViaFabric is a dependency of ViaBackwards and ViaVersion
      # 📦 Starter Kit gives new players configurable starting items # https://modrinth.com/mod/starter-kit
      # Collective is a dependency of starter-kit
      # Villager Names 🧑‍🌾 Gives all villager entities a default or custom name to liven up the world.  # https://modrinth.com/mod/villager-names-serilum
      # The simplest multiplayer sleep mod/datapack. - Changes playersSleepingPercentage to 50%  # https://modrinth.com/datapack/serversleep
      # Nature's compass Allows you to locate biomes anywhere in the world with a friendly GUI.  # https://modrinth.com/mod/natures-compass
      MODRINTH_PROJECTS: |
        tectonic
        lithostitched
        viaversion
        viabackwards
        viafabric:alpha
        starter-kit
        collective
        villager-names-serilum
        serversleep
        # natures-compass
      # Datapacks from vanilla tweaks (comma separated IDs like kSIhW5,2e96zb)
      # graves gravestone https://vanillatweaks.net/picker/datapacks/#kSIhW5
      # multiplayer sleep https://vanillatweaks.net/picker/datapacks/#Uw9c10
      # classic fishing loot vanillatweaks.net/share#2e96zb
      VANILLATWEAKS_SHARECODE: ""
      # RAM parameters
      MEMORY: "10G"
      INIT_MEMORY: "10G"
      # Server settings
      DIFFICULTY: "hard"
      MAX_PLAYERS: "17"
      VIEW_DISTANCE: "8"
      SIMULATION_DISTANCE: "8"
      # Keep ops list off github, use private.env
      OPS: ${OPS_LIST}
      CREATE_CONSOLE_IN_PIPE: "true" # Allow mc-send-to-console
